import{a as l,i,S as u}from"./assets/vendor-tnUJPedx.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const f="48848365-f4e25352a2e58b0aa69d4606d",p="https://pixabay.com/api/";async function d(s){const r=`${p}?key=${f}&q=${encodeURIComponent(s)}&image_type=photo`;try{return(await l.get(r)).data.hits}catch(o){throw console.error("Error fetching images:",o),o}}function m(s){const r=document.querySelector(".gallery");if(r.innerHTML="",s.length===0){i.error({title:"Error",message:"Sorry, no images found. Please try another search!",position:"topRight"});return}const o=s.map(({previewURL:a,largeImageURL:e,tags:t})=>`<li class="gallery-item">
          <a class="gallery-link" href="${e}">
            <img class="gallery-image"
                 src="${a}"
                 data-source="${e}"
                 alt="${t}" />
          </a>
        </li>`).join("");r.insertAdjacentHTML("beforeend",o),new u(".gallery a",{captionsData:"alt",captionDelay:250})}const c=document.querySelector(".search-form"),g=c.querySelector("input[name='text']");c.addEventListener("submit",async s=>{s.preventDefault();const r=g.value.trim();if(r===""){i.warning({title:"Warning",message:"Please enter a search query!",position:"topRight"});return}try{const o=await d(r);m(o)}catch{i.error({title:"Error",message:"Failed to fetch images. Please try again!",position:"topRight"})}});
//# sourceMappingURL=index.js.map
